_links:
  self:
    href: https://vsrm.dev.azure.com/slb-swt/2e3159a5-e2ec-4479-8cf7-0d797e815202/_apis/Release/definitions/6
  web:
    href: https://dev.azure.com/slb-swt/2e3159a5-e2ec-4479-8cf7-0d797e815202/_release?definitionId=6
artifacts:
- alias: _prodops-components tests
  definitionReference:
    IsMultiDefinitionType:
      id: 'False'
      name: 'False'
    artifactSourceDefinitionUrl:
      id: https://dev.azure.com/slb-swt/_permalink/_build/index?collectionId=60eae5f9-3e4d-4c8a-a560-89c460efb732&projectId=2e3159a5-e2ec-4479-8cf7-0d797e815202&definitionId=2545
      name: ''
    defaultVersionBranch:
      id: ''
      name: ''
    defaultVersionSpecific:
      id: ''
      name: ''
    defaultVersionTags:
      id: ''
      name: ''
    defaultVersionType:
      id: selectDuringReleaseCreationType
      name: Specify at the time of release creation
    definition:
      id: '2545'
      name: prodops-components tests
    definitions:
      id: ''
      name: ''
    project:
      id: 2e3159a5-e2ec-4479-8cf7-0d797e815202
      name: assetops
    repository:
      id: 7f31f373-f47e-4808-a592-08d92c4e00ad
      name: misc_pwe_samples
  isPrimary: true
  isRetained: false
  sourceId: 2e3159a5-e2ec-4479-8cf7-0d797e815202:2545
  type: Build
createdBy:
  _links:
    avatar:
      href: https://dev.azure.com/slb-swt/_apis/GraphProfile/MemberAvatars/aad.MGU0MTgwOWUtOTlkYi03MTViLTkyYzgtNmE3ZjNiYTUzMmUy
  descriptor: aad.MGU0MTgwOWUtOTlkYi03MTViLTkyYzgtNmE3ZjNiYTUzMmUy
  displayName: Leandro Santos
  id: cf403b0d-0bf6-4258-85d3-7e362375b876
  imageUrl: https://dev.azure.com/slb-swt/_api/_common/identityImage?id=cf403b0d-0bf6-4258-85d3-7e362375b876
  uniqueName: LSantos10@slb.com
  url: https://app.vssps.visualstudio.com/A3f415df3-7ced-4236-a01d-d1d222cd0429/_apis/Identities/cf403b0d-0bf6-4258-85d3-7e362375b876
createdOn: '2018-11-12T15:03:31.44Z'
description: Hello World!
environments:
- badgeUrl: https://vsrm.dev.azure.com/slb-swt/_apis/public/Release/badge/2e3159a5-e2ec-4479-8cf7-0d797e815202/6/160
  conditions:
  - conditionType: event
    name: ReleaseStarted
    value: ''
  - conditionType: artifact
    name: _prodops-components tests
    value: '{"sourceBranch":"master","tags":[],"useBuildDefinitionBranch":false,"createReleaseOnBuildTagging":false}'
  currentRelease:
    _links: {}
    id: 1583
    url: https://vsrm.dev.azure.com/slb-swt/2e3159a5-e2ec-4479-8cf7-0d797e815202/_apis/Release/releases/1583
  demands: []
  deployPhases:
  - deploymentInput:
      artifactsDownloadInput:
        downloadInputs: []
      condition: succeeded()
      demands: []
      enableAccessToken: false
      jobCancelTimeoutInMinutes: 1
      overrideInputs: {}
      parallelExecution:
        parallelExecutionType: none
      queueId: 584
      skipArtifactsDownload: false
      timeoutInMinutes: 0
    name: Agent job
    phaseType: agentBasedDeployment
    rank: 1
    refName: null
    workflowTasks: []
  deployStep:
    id: 503
  environmentOptions:
    autoLinkWorkItems: false
    badgeEnabled: false
    emailNotificationType: OnlyOnFailure
    emailRecipients: release.environment.owner;release.creator
    enableAccessToken: false
    publishDeploymentStatus: true
    pullRequestDeploymentEnabled: false
    skipArtifactsDownload: false
    timeoutInMinutes: 0
  environmentTriggers: []
  executionPolicy:
    concurrencyCount: 1
    queueDepthCount: 0
  id: 160
  name: Stage 2 - Testing
  owner:
    _links:
      avatar:
        href: https://dev.azure.com/slb-swt/_apis/GraphProfile/MemberAvatars/aad.MGU0MTgwOWUtOTlkYi03MTViLTkyYzgtNmE3ZjNiYTUzMmUy
    descriptor: aad.MGU0MTgwOWUtOTlkYi03MTViLTkyYzgtNmE3ZjNiYTUzMmUy
    displayName: Leandro Santos
    id: cf403b0d-0bf6-4258-85d3-7e362375b876
    imageUrl: https://dev.azure.com/slb-swt/_api/_common/identityImage?id=cf403b0d-0bf6-4258-85d3-7e362375b876
    uniqueName: LSantos10@slb.com
    url: https://app.vssps.visualstudio.com/A3f415df3-7ced-4236-a01d-d1d222cd0429/_apis/Identities/cf403b0d-0bf6-4258-85d3-7e362375b876
  postDeployApprovals:
    approvalOptions:
      autoTriggeredAndPreviousEnvironmentApprovedCanBeSkipped: false
      enforceIdentityRevalidation: false
      executionOrder: afterSuccessfulGates
      releaseCreatorCanBeApprover: true
      requiredApproverCount: null
      timeoutInMinutes: 0
    approvals:
    - approver:
        _links:
          avatar:
            href: https://dev.azure.com/slb-swt/_apis/GraphProfile/MemberAvatars/aad.ODI1OGRlMmUtZTA4NS03YmZiLTg0ZDYtNThhMmVjMzY3YmEw
        descriptor: aad.ODI1OGRlMmUtZTA4NS03YmZiLTg0ZDYtNThhMmVjMzY3YmEw
        displayName: Zhanybek Mamataliev
        id: 8258de2e-e085-6bfb-84d6-58a2ec367ba0
        imageUrl: https://dev.azure.com/slb-swt/_api/_common/identityImage?id=8258de2e-e085-6bfb-84d6-58a2ec367ba0
        uniqueName: ZMamataliev@slb.com
        url: https://app.vssps.visualstudio.com/A3f415df3-7ced-4236-a01d-d1d222cd0429/_apis/Identities/8258de2e-e085-6bfb-84d6-58a2ec367ba0
      id: 524
      isAutomated: false
      isNotificationOn: false
      rank: 1
  postDeploymentGates:
    gates: []
    gatesOptions: null
    id: 0
  preDeployApprovals:
    approvalOptions:
      autoTriggeredAndPreviousEnvironmentApprovedCanBeSkipped: false
      enforceIdentityRevalidation: false
      executionOrder: beforeGates
      releaseCreatorCanBeApprover: false
      requiredApproverCount: null
      timeoutInMinutes: 0
    approvals:
    - id: 500
      isAutomated: true
      isNotificationOn: false
      rank: 1
  preDeploymentGates:
    gates: []
    gatesOptions: null
    id: 0
  processParameters: {}
  properties: {}
  rank: 1
  retentionPolicy:
    daysToKeep: 30
    releasesToKeep: 3
    retainBuild: true
  schedules: []
  variableGroups: []
  variables: {}
- badgeUrl: https://vsrm.dev.azure.com/slb-swt/_apis/public/Release/badge/2e3159a5-e2ec-4479-8cf7-0d797e815202/6/161
  conditions:
  - conditionType: environmentState
    name: Stage 2 - Testing
    value: '4'
  currentRelease:
    _links: {}
    id: 1583
    url: https://vsrm.dev.azure.com/slb-swt/2e3159a5-e2ec-4479-8cf7-0d797e815202/_apis/Release/releases/1583
  demands: []
  deployPhases:
  - deploymentInput:
      artifactsDownloadInput:
        downloadInputs: []
      condition: succeeded()
      demands: []
      enableAccessToken: false
      jobCancelTimeoutInMinutes: 1
      overrideInputs: {}
      parallelExecution:
        parallelExecutionType: none
      queueId: 584
      skipArtifactsDownload: false
      timeoutInMinutes: 0
    name: Agent job
    phaseType: agentBasedDeployment
    rank: 1
    refName: null
    workflowTasks: []
  deployStep:
    id: 502
  environmentOptions:
    autoLinkWorkItems: false
    badgeEnabled: false
    emailNotificationType: OnlyOnFailure
    emailRecipients: release.environment.owner;release.creator
    enableAccessToken: false
    publishDeploymentStatus: true
    pullRequestDeploymentEnabled: false
    skipArtifactsDownload: false
    timeoutInMinutes: 0
  environmentTriggers: []
  executionPolicy:
    concurrencyCount: 1
    queueDepthCount: 1
  id: 161
  name: Manoj Stage 4
  owner:
    displayName: null
    id: cf403b0d-0bf6-4258-85d3-7e362375b877
  postDeployApprovals:
    approvalOptions:
      autoTriggeredAndPreviousEnvironmentApprovedCanBeSkipped: false
      enforceIdentityRevalidation: false
      executionOrder: afterSuccessfulGates
      releaseCreatorCanBeApprover: false
      requiredApproverCount: null
      timeoutInMinutes: 0
    approvals:
    - id: 505
      isAutomated: true
      isNotificationOn: false
      rank: 1
  postDeploymentGates:
    gates: []
    gatesOptions: null
    id: 0
  preDeployApprovals:
    approvalOptions:
      autoTriggeredAndPreviousEnvironmentApprovedCanBeSkipped: false
      enforceIdentityRevalidation: false
      executionOrder: beforeGates
      releaseCreatorCanBeApprover: false
      requiredApproverCount: null
      timeoutInMinutes: 0
    approvals:
    - id: 501
      isAutomated: true
      isNotificationOn: false
      rank: 1
  preDeploymentGates:
    gates: []
    gatesOptions: null
    id: 0
  processParameters: {}
  properties: {}
  rank: 2
  retentionPolicy:
    daysToKeep: 30
    releasesToKeep: 3
    retainBuild: true
  schedules: []
  variableGroups: []
  variables: {}
- badgeUrl: https://vsrm.dev.azure.com/slb-swt/_apis/public/Release/badge/2e3159a5-e2ec-4479-8cf7-0d797e815202/6/168
  conditions:
  - conditionType: environmentState
    name: Stage 2 - Testing
    value: '4'
  currentRelease:
    _links: {}
    id: 0
    url: https://vsrm.dev.azure.com/slb-swt/2e3159a5-e2ec-4479-8cf7-0d797e815202/_apis/Release/releases/0
  demands: []
  deployPhases:
  - deploymentInput:
      artifactsDownloadInput:
        downloadInputs: []
      condition: succeeded()
      demands: []
      enableAccessToken: false
      jobCancelTimeoutInMinutes: 1
      overrideInputs: {}
      parallelExecution:
        parallelExecutionType: none
      queueId: 584
      skipArtifactsDownload: false
      timeoutInMinutes: 0
    name: Agent job
    phaseType: agentBasedDeployment
    rank: 1
    refName: null
    workflowTasks: []
  deployStep:
    id: 529
  environmentOptions:
    autoLinkWorkItems: false
    badgeEnabled: false
    emailNotificationType: OnlyOnFailure
    emailRecipients: release.environment.owner;release.creator
    enableAccessToken: false
    publishDeploymentStatus: true
    pullRequestDeploymentEnabled: false
    skipArtifactsDownload: false
    timeoutInMinutes: 0
  environmentTriggers: []
  executionPolicy:
    concurrencyCount: 1
    queueDepthCount: 0
  id: 168
  name: Copy of Stage 2 - Testing
  owner:
    _links:
      avatar:
        href: https://dev.azure.com/slb-swt/_apis/GraphProfile/MemberAvatars/aad.MGU0MTgwOWUtOTlkYi03MTViLTkyYzgtNmE3ZjNiYTUzMmUy
    descriptor: aad.MGU0MTgwOWUtOTlkYi03MTViLTkyYzgtNmE3ZjNiYTUzMmUy
    displayName: Leandro Santos
    id: cf403b0d-0bf6-4258-85d3-7e362375b876
    imageUrl: https://dev.azure.com/slb-swt/_api/_common/identityImage?id=cf403b0d-0bf6-4258-85d3-7e362375b876
    uniqueName: LSantos10@slb.com
    url: https://app.vssps.visualstudio.com/A3f415df3-7ced-4236-a01d-d1d222cd0429/_apis/Identities/cf403b0d-0bf6-4258-85d3-7e362375b876
  postDeployApprovals:
    approvalOptions:
      autoTriggeredAndPreviousEnvironmentApprovedCanBeSkipped: false
      enforceIdentityRevalidation: false
      executionOrder: afterSuccessfulGates
      releaseCreatorCanBeApprover: true
      requiredApproverCount: null
      timeoutInMinutes: 0
    approvals:
    - approver:
        _links:
          avatar:
            href: https://dev.azure.com/slb-swt/_apis/GraphProfile/MemberAvatars/aad.ODI1OGRlMmUtZTA4NS03YmZiLTg0ZDYtNThhMmVjMzY3YmEw
        descriptor: aad.ODI1OGRlMmUtZTA4NS03YmZiLTg0ZDYtNThhMmVjMzY3YmEw
        displayName: Zhanybek Mamataliev
        id: 8258de2e-e085-6bfb-84d6-58a2ec367ba0
        imageUrl: https://dev.azure.com/slb-swt/_api/_common/identityImage?id=8258de2e-e085-6bfb-84d6-58a2ec367ba0
        uniqueName: ZMamataliev@slb.com
        url: https://app.vssps.visualstudio.com/A3f415df3-7ced-4236-a01d-d1d222cd0429/_apis/Identities/8258de2e-e085-6bfb-84d6-58a2ec367ba0
      id: 530
      isAutomated: false
      isNotificationOn: false
      rank: 1
  postDeploymentGates:
    gates: []
    gatesOptions: null
    id: 0
  preDeployApprovals:
    approvalOptions:
      autoTriggeredAndPreviousEnvironmentApprovedCanBeSkipped: false
      enforceIdentityRevalidation: false
      executionOrder: beforeGates
      releaseCreatorCanBeApprover: false
      requiredApproverCount: null
      timeoutInMinutes: 0
    approvals:
    - id: 528
      isAutomated: true
      isNotificationOn: false
      rank: 1
  preDeploymentGates:
    gates: []
    gatesOptions: null
    id: 0
  processParameters: {}
  properties: {}
  rank: 3
  retentionPolicy:
    daysToKeep: 30
    releasesToKeep: 3
    retainBuild: true
  schedules: []
  variableGroups: []
  variables: {}
id: 6
isDeleted: false
modifiedBy:
  _links:
    avatar:
      href: https://dev.azure.com/slb-swt/_apis/GraphProfile/MemberAvatars/aad.ODI1OGRlMmUtZTA4NS03YmZiLTg0ZDYtNThhMmVjMzY3YmEw
  descriptor: aad.ODI1OGRlMmUtZTA4NS03YmZiLTg0ZDYtNThhMmVjMzY3YmEw
  displayName: Zhanybek Mamataliev
  id: 8258de2e-e085-6bfb-84d6-58a2ec367ba0
  imageUrl: https://dev.azure.com/slb-swt/_api/_common/identityImage?id=8258de2e-e085-6bfb-84d6-58a2ec367ba0
  uniqueName: ZMamataliev@slb.com
  url: https://app.vssps.visualstudio.com/A3f415df3-7ced-4236-a01d-d1d222cd0429/_apis/Identities/8258de2e-e085-6bfb-84d6-58a2ec367ba0
modifiedOn: '2019-03-18T23:07:32.277Z'
name: New release pipeline
path: \
pipelineProcess:
  type: designer
projectReference: null
properties:
  DefinitionCreationSource:
    $type: System.String
    $value: Other
releaseNameFormat: Release-$(rev:r)
revision: 14
source: userInterface
tags: []
triggers: []
url: https://vsrm.dev.azure.com/slb-swt/2e3159a5-e2ec-4479-8cf7-0d797e815202/_apis/Release/definitions/6
variableGroups: []
variables: {}
